Repository bcgov/nr-fom, pull requests merged in 2022-06, with the labels that each got.

#6 nr-fom-api merge revisions
  .github/openshift/deploy.backend.yml
  .github/openshift/deploy.database.yml
  .github/openshift/deploy.frontend.yml
  .github/openshift/networkPolicies.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  .github/workflows/sonarcloud.yml
Labels: enhancement

#14 Clean up configmap
  .github/workflows/pr-close.yml
Labels: bug

#24 GHCR_TOKEN for docker in pipeline
  .github/workflows/pr-open.yml
Labels: bug

#21 Enable CORS for API
  .github/openshift/deploy.api.yml
  apps/api/src/main.ts
Labels: enhancement

#42 Update deployment links for TEST and PROD
  .github/workflows/pr-open.yml
Labels: bug

#69 Feat/sonarcloud
  .github/workflows/sonarcloud.yml
  .gitignore
Labels: enhancement

#79 Feat/cronjobs
  .github/openshift/deploy.api.yml
  .github/workflows/pr-open.yml
Labels: enhancement

#83 Move oc prod cleanup to pr-open b/c access prompts
  .github/workflows/merge-main.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
Labels: bug, enhancement

#84 Add ca-certificates via /etc/pki to API
  api/Dockerfile
Labels: bug, enhancement
